import { parseAbi } from "viem";

/** Custom error kontrak (dihasilkan dari artefak forge). Disertakan di ABI supaya revert terbaca sebagai nama error. */
export const contractErrors = parseAbi([
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account,bytes32 neededRole)",
  "error AlreadyLocked()",
  "error TransferNotOpen()",
  "error IndependentRequired()",
  "error SelfTransfer()",
  "error AlreadyReleased()",
  "error BadNonce()",
  "error BadParams()",
  "error BadPeriod()",
  "error BadSignature()",
  "error BadSigners()",
  "error BadTerms()",
  "error BadVerdict()",
  "error CapExceeded()",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256 length)",
  "error ECDSAInvalidSignatureS(bytes32 s)",
  "error ERC20InsufficientAllowance(address spender,uint256 allowance,uint256 needed)",
  "error ERC20InsufficientBalance(address sender,uint256 balance,uint256 needed)",
  "error ERC20InvalidApprover(address approver)",
  "error ERC20InvalidReceiver(address receiver)",
  "error ERC20InvalidSender(address sender)",
  "error ERC20InvalidSpender(address spender)",
  "error EnforcedPause()",
  "error ExceptionIsOpen()",
  "error ExpectedPause()",
  "error Expired()",
  "error ExpiryTooFar()",
  "error InsufficientBalance()",
  "error InvalidShortString()",
  "error NoSupply()",
  "error NoValidAttestation()",
  "error NotAllowlisted(address to)",
  "error NotApproved()",
  "error NotAttested()",
  "error NotAuditor()",
  "error NotEnoughSignatures(uint256 have,uint256 need)",
  "error NotFunded()",
  "error NotHead()",
  "error NotPending()",
  "error NotRequester()",
  "error NotSigner()",
  "error NotValid()",
  "error NothingToRefund()",
  "error OfferingEnded()",
  "error OfferingNotEnded()",
  "error OnlySeries()",
  "error OverrideNeedsReason()",
  "error PaymentRefReused()",
  "error PeriodNotClean()",
  "error PriceAboveMax()",
  "error RedeemClosed()",
  "error ReentrancyGuardReentrantCall()",
  "error RootAlreadyAnchored()",
  "error ShareTooHigh()",
  "error SignatureExpired()",
  "error SignersNotAscending()",
  "error StringTooLong(string str)",
  "error SymbolTooLong()",
  "error TenorEnded()",
  "error TenorNotEnded()",
  "error TotalShareTooHigh()",
  "error Tranche1First()",
  "error TransfersLocked()",
  "error WrongState(uint8 have)",
  "error ZeroPayout()",
  "error ZeroUnits()",
]);
