export interface Slide {
  title: string;
  chapter: string;
  className?: string;
  body: string;
  source: string;
  notes: string;
  seconds: number;
}

export const sources = [
  { id: 'S1', title: 'BPS · Sports facilities by village, 2024', url: 'https://www.bps.go.id/id/statistics-table/2/OTc0IzI%3D/number-of-villages-according-availability-sport-field.html', detail: '14,253 villages/kelurahan with futsal; 36,540 badminton; 48,886 football. Units are villages, not individual courts. Categories can overlap. Not a count of commercially operated or eligible venues; not TAM.' },
  { id: 'S2', title: 'AYO · Official website', url: 'https://ayo.co/', detail: 'Company-reported: 900,000+ users, 100+ cities, 2,000+ sports facilities, 6,800+ bookable courts. Accessed 10 October 2026. Not government statistics, Open Grounds traction, or a partnership.' },
  { id: 'S3', title: 'Jurnal Logistica · Futsal feasibility study, 2024', url: 'https://journal.iteba.ac.id/index.php/logistica/article/view/304', detail: 'Asmarawati, Sidabutar & Wibowo; DOI 10.62375/logistics.v2i2.304; published 21 June 2024. Abstract reports NPV +Rp38,812,042, IRR 7%, payback 9 months for one Batam business. This does not establish market-wide returns. Cost-table inconsistencies limit generalization.' },
  { id: 'S3 PDF', title: 'Original research PDF · pp. 56–60', url: 'https://journal.iteba.ac.id/index.php/logistica/article/download/304/189', detail: 'Original paper reviewed. Maintenance is only one expense line; do not equate it with total OPEX. Reusable-asset framing is our interpretation of recurring court rentals, not a published market statistic.' },
  { id: 'P1', title: 'Open Grounds · Product repository', url: 'https://github.com/senarais/opengrounds', detail: 'Product model: local Open_Grounds_PRD_v4.1_Hackathon.md (9 October 2026), identical to OG_PRD_v4.1.md at review time. AGENTS.md contains later decisions on review signatures, attestation policies, Privy and sandbox payments; those override older PRD text. Implementation is not proof of production readiness.' },
  { id: 'D1', title: 'Saku Pitch · Design reference', url: 'https://github.com/s-erzv/saku-pitch', detail: 'Reference for warm orange accents, large typography, modular compositions and a web-native printable presentation. This deck has original layouts and code; no Saku mascot or app assets copied.' },
  { id: 'A1', title: 'Unsplash · Sports photography', url: 'https://unsplash.com/license', detail: 'Existing project photos: images.unsplash.com/photo-1595435934249-5df7ed86e1c0 photo-1554068865-24cecd4e34b8 and photo-1546519638-68e109498ffc. Illustrative photography only; not listed venues or customer evidence. Fonts: Plus Jakarta Sans and Inter, SIL Open Font License, bundled via Fontsource.' },
];

export const slides: Slide[] = [
  {
    title: 'Open Grounds', chapter: 'The opportunity', className: 'cover', seconds: 20,
    body: `<div class="cover-photo"><img src="/assets/player.jpg" alt="Clay tennis court from above, illustrative photography"/></div><div class="cover-copy"><div class="event-tag">ETHJKT 2026 / RWA track</div><h1>Open<br>Grounds.</h1><p class="cover-tagline">Fractional access.<br>Real venue profits.</p><p class="cover-detail">For the places where people play.</p><div class="cover-mark">Sports venues → Shared economic rights</div></div><div class="serve-visual" aria-hidden="true"><svg viewBox="0 0 600 450"><path class="serve-trail" pathLength="1" d="M40 335 Q190 65 525 150" fill="none" stroke="#F8FAFC" stroke-width="3"/><circle class="serve-point" cx="525" cy="150" r="8" fill="#F8FAFC"/></svg><span class="serve-ball"></span></div><div class="cover-signature">Open the upside.</div><span class="photo-label">Illustrative court photography</span>`, 
    source: 'Ethereum Sepolia · Testnet / simulation',
    notes: 'Bayangin lapangan yang sama disewa berkali-kali. Ada aktivitas nyata, ada pembayaran, ada laba. Open Grounds membuka akses fractional ke hak manfaat ekonomi atas sebagian laba bersih venue olahraga. Jangan sebut token sebagai kepemilikan tanah atau saham PT. Tagline draft teman disempurnakan agar maknanya tepat. Ini proyek hackathon di Sepolia, bukan penawaran investasi publik.',
  },
  {
    title: 'The venue earns. Access stays closed.', chapter: 'The problem', className: 'problem', seconds: 30,
    body: `<div class="problem-top"><h2>The venue earns.<br>Access stays closed.</h2><div class="evidence-split" aria-label="Booking, payment and expense evidence are fragmented"><span>Booking</span><span>Payment</span><span>Expenses</span><svg viewBox="0 0 460 70" aria-hidden="true"><path pathLength="1" d="M40 20h70m20 0h70m20 0h70m20 0h90" fill="none" stroke="#94A3B8" stroke-width="2" stroke-dasharray="6 6"/><path class="broken-link" d="M120 7l-10 25m110-25l-10 25m110-25l-10 25" stroke="#c25a00" stroke-width="4"/></svg><b>Three records. No shared view.</b></div></div><div class="problem-rows"><article><h3>Owners need<br>growth capital.</h3><p>Renovation or another court?<br>Often funded by own cash,<br>debt or a large investor.</p><div class="problem-label">Capital gap</div></article><article><h3>Retail investors<br>can’t easily join.</h3><p>Productive venues are hard<br>to access through small,<br>transparent investment units.</p><div class="problem-label">Access gap</div></article><article><h3>Performance is<br>hard to verify.</h3><p>Revenue and expenses live<br>in separate systems.<br>Investor trust starts with evidence.</p><div class="problem-label">Evidence gap</div></article></div><div class="thesis">Productive venues need capital. Investors need a credible way in.</div>`, 
    source: 'Problem thesis · A hypothesis to validate with owners and investors',
    notes: 'Owner punya bisnis produktif, tapi saat mau menambah court atau renovasi, opsi modalnya terbatas. Investor retail di sisi lain sulit ikut manfaat ekonomi venue tersebut. Masalah ketiga mengikat dua masalah pertama: data booking, pembayaran, dan biaya terpisah. Kalau kita sekadar mencetak token, gap kepercayaan belum selesai. Ini hipotesis problem dari PRD, bukan hasil survei pelanggan yang sudah kita jalankan.',
  },
  {
    title: 'Keep operating. Open the profit rights.', chapter: 'The solution', className: 'solution', seconds: 45,
    body: `<h2>Keep operating.<br>Open the profit rights.</h2><p class="lead">Capital for the owner. Fractional participation for the investor.</p><div class="solution-route"><article class="route-owner"><svg viewBox="0 0 240 115" fill="none" aria-hidden="true"><path d="M15 27L172 9l54 60-159 35z" fill="#FF7A00"/><g stroke="#F8FAFC" stroke-width="2"><path d="M32 34l132-16 44 48-133 29zM98 26l44 49M50 54l132-16M64 75l131-16"/><path d="M38 105h174" stroke="#94A3B8"/></g></svg><h3>Venue owner</h3><p>Sells X% of distributable<br>net-profit rights.</p><b>Receives upfront capital</b></article><div class="route-pass"><svg viewBox="0 0 135 160" aria-hidden="true"><path class="route-line" pathLength="1" d="M5 65h115m-12-10l12 10-12 10M120 108H5m12-10L5 108l12 10" fill="none" stroke="#c25a00" stroke-width="3"/></svg></div><article class="route-platform"><img src="/assets/og-logo.png" alt=""/><h3>Grounds +<br>Open Grounds</h3><p>SPV acquires the rights.<br>Platform verifies and services them.</p><b>Evidence → Fractional units</b></article><div class="route-pass"><svg viewBox="0 0 135 160" aria-hidden="true"><path class="route-line" pathLength="1" d="M5 65h115m-12-10l12 10-12 10M120 108H5m12-10L5 108l12 10" fill="none" stroke="#c25a00" stroke-width="3"/></svg></div><article class="route-investors"><svg class="token-units" viewBox="0 0 240 115" aria-hidden="true"><rect x="16" y="15" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="59" y="15" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="102" y="15" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="145" y="15" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="188" y="15" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="16" y="57" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="59" y="57" width="31" height="31" rx="2" fill="#FF7A00"/><rect x="102" y="57" width="31" height="31" rx="2" fill="#cbd5e1"/><rect x="145" y="57" width="31" height="31" rx="2" fill="#cbd5e1"/><rect x="188" y="57" width="31" height="31" rx="2" fill="#cbd5e1"/></svg><h3>Investors</h3><p>Buy units with rupiah.<br>Receive a proportional profit share.</p><b>KYC + Signed orders</b></article></div><div class="distribution-lane"><span>Venue activity</span><div class="lane-line"><i class="cash-dot"></i></div><span>Verified net profit</span><div class="lane-line"><i class="cash-dot"></i></div><span>Monthly investor balance</span></div><div class="solution-proof"><b>Ethereum is the referee.</b><span>Signed orders · Exact payments · Expense caps · Monthly approvals</span></div><p class="fine-risk">Economic rights, not land. Token ini tidak dijamin oleh aset venue. Returns and liquidity are not guaranteed.</p>`, 
    source: 'Upfront acquisition payment and rupiah rails simulated in the hackathon',
    notes: 'Owner menjual X% hak manfaat ekonomi atas laba bersih yang bisa dibagikan ke Grounds, SPV pembeli hak sekaligus penerbit token. Grounds membayar owner di depan; di demo ini disimulasikan. Token dicetak sekali ke treasury lalu dijual berkelanjutan. Investor beli dengan rupiah, KYC dan rekening nama sendiri, serta menandatangani order lewat Privy. Uang wajib masuk sebelum alokasi. Venue tetap dioperasikan owner, laporan laba disahkan, lalu dana distribusi masuk saldo ledger investor untuk ditarik atau reinvest. Hak ini bukan omzet, tanah, atau saham PT. Tidak ada tenor atau burn, transfer antar investor dilarang. Jual balik hanya saat lot terbuka, seri Active dan cadangan treasury tersedia; tidak dijamin. Bentuk hukum, izin dan struktur SPV produksi masih terbuka; jangan memilih bentuk hukum seolah sudah final.',
  },
  {
    title: 'The courts are already here.', chapter: 'The market', className: 'market', seconds: 35,
    body: `<h2>The courts are already here.</h2><div class="market-layout"><div class="market-reach"><h3>Villages with sports facilities</h3><p class="chart-caption">Indonesia, 2024 · Number of desa/kelurahan [S1]</p><svg class="facility-chart" viewBox="0 0 940 350" role="img" aria-label="BPS 2024: 48,886 villages with football, 36,540 badminton and 14,253 futsal facilities. These count villages, not courts."><g stroke="#dbe2ea" stroke-width="1"><path d="M165 35v269"/><path d="M289 35v269"/><path d="M413 35v269"/><path d="M537 35v269"/><path d="M661 35v269"/><path d="M785 35v269"/></g><g fill="#334155" font-size="17"><text x="165" y="336" text-anchor="middle">0</text><text x="289" y="336" text-anchor="middle">10k</text><text x="413" y="336" text-anchor="middle">20k</text><text x="537" y="336" text-anchor="middle">30k</text><text x="661" y="336" text-anchor="middle">40k</text><text x="785" y="336" text-anchor="middle">50k</text></g><text x="0" y="90" fill="#0F172A" font-size="24" font-weight="600">Football</text><rect class="chart-bar bar-0" x="165" y="64" width="606.1864" height="40" fill="#334155"/><text class="chart-value" x="783.1864" y="91" fill="#0F172A" font-size="23" font-weight="700" data-count="48886">48,886</text><text x="0" y="180" fill="#0F172A" font-size="24" font-weight="600">Badminton</text><rect class="chart-bar bar-1" x="165" y="154" width="453.096" height="40" fill="#94A3B8"/><text class="chart-value" x="630.096" y="181" fill="#0F172A" font-size="23" font-weight="700" data-count="36540">36,540</text><text x="0" y="270" fill="#0F172A" font-size="24" font-weight="600">Futsal</text><rect class="chart-bar bar-2" x="165" y="244" width="176.7372" height="40" fill="#c25a00"/><text class="chart-value" x="353.73720000000003" y="271" fill="#0F172A" font-size="23" font-weight="700" data-count="14253">14,253</text></svg><p class="chart-caveat">Counts villages, not courts. Categories can overlap.<br>Does not measure commercial venue eligibility or investment TAM.</p></div><aside class="booking-score"><span>Digital bookings / AYO [S2]</span><strong data-count="6800" data-suffix="+">6,800+</strong><h3>courts to book</h3><div class="booking-mini"><b data-count="900000" data-suffix="+">900,000+</b><span>users</span></div><div class="booking-mini"><b data-count="100" data-suffix="+">100+</b><span>cities</span></div><small>2,000+ sports facilities.<br>Company-reported, not our traction.</small></aside></div><div class="market-case"><div><span>Single-venue evidence / Batam, 2024 [S3]</span><h3>+Rp38.8m reported NPV</h3></div><p>IRR 7% · Payback ≈9 months<br>One case, not a return forecast.</p><div class="repeated-rental"><b>Same court. Repeated rentals.</b><span>Reusable asset framing is our interpretation.</span></div></div>`, 
    source: 'Sources: [S1] BPS (2024) · [S2] AYO (accessed 10 Oct 2026) · [S3] Jurnal Logistica (2024)',
    notes: 'Pasarnya sudah ada; kita tidak menciptakan kebiasaan olahraga baru. BPS mencatat 14.253 desa/kelurahan dengan fasilitas futsal pada 2024. Itu bukan jumlah court dan bukan jumlah venue yang memenuhi syarat Open Grounds. Rincian AYO: 2.000+ fasilitas olahraga; 3.700+ padel, 1.400+ badminton, 400+ tennis, 200+ mini soccer dan 200+ futsal courts. Ini company-reported dan tidak dijumlahkan sebagai TAM. Data AYO menunjukkan booking sudah digital: lebih dari 6.800 court, 900 ribu pengguna, di lebih dari 100 kota. AYO bukan partner kita. Studi Batam melaporkan NPV positif, IRR 7%, payback sembilan bulan, tetapi hanya satu studi kasus dan tabel biayanya punya inkonsistensi. Pakai untuk menunjukkan potensi kelayakan usaha, jangan untuk menjanjikan return. Tidak ada klaim OPEX hanya Rp2 juta. Data BPS dan AYO tidak dijumlahkan menjadi TAM.',
  },
  {
    title: 'A business built around verified cash flow.', chapter: 'Business model canvas', className: 'bmc-slide', seconds: 40,
    body: `<h2>A business built around<br>verified cash flow.</h2><span class="bmc-label">Business model canvas · Proposed model, pre-validation</span><div class="bmc"><article class="partners"><h3>Key partners</h3><p>Venue owners<br>Independent reviewers<br>Licensed payment rails¹<br>Legal & valuation advisors¹</p></article><article class="activities"><h3>Key activities</h3><p>KYB & reconciliation<br>Rights structuring<br>Token servicing<br>Distribution operations</p></article><article class="resources"><h3>Key resources</h3><p>Venue OS / PoS<br>Verified data & contracts<br>SPV capital & reserves¹</p></article><article class="value"><h3>Value propositions</h3><p><b>Owners</b><br>Upfront growth capital;<br>continue operating.</p><p><b>Investors</b><br>Fractional profit access;<br>visible rules & reporting.</p></article><article class="relations"><h3>Customer relationships</h3><p>Assisted owner onboarding<br>Investor self-service<br>Monthly performance reports</p></article><article class="channels"><h3>Channels</h3><p>Open Grounds web<br>Venue operator networks²<br>Sports communities²</p></article><article class="segments"><h3>Customer segments</h3><p>Owners with owned land,<br>≥12-month history,<br>≥90% digital revenue.</p><p>KYC-approved investors<br>seeking venue exposure.</p></article><article class="costs"><h3>Cost structure</h3><p>Verification & operations · Legal & valuation¹ · Technology & payment costs<br>Grounds: upfront acquisition capital + liquidity reserves</p></article><article class="revenue"><h3>Revenue streams</h3><p><b>Open Grounds:</b> recurring platform fee (rate undecided).<br><b>Grounds:</b> SPV management fee, 2% [Asumsi] of SPV profit share.</p></article></div><div class="bmc-footnote">¹ Production dependencies; not confirmed partnerships. ² Proposed acquisition channels. No POS subscription or issuance-fee revenue assumed.</div>`,
    source: 'Platform fee, legal structure and SPV funding remain open decisions',
    notes: 'Bisnis dibangun di sekitar servicing venue yang sudah produktif, bukan spekulasi harga token. Owner target harus punya tanah sendiri tidak dijaminkan, histori minimal 12 bulan dan pendapatan digital minimal 90%. Investor wajib KYC dan rekening nama sendiri. Nilainya untuk owner adalah modal di depan sambil tetap operasi; untuk investor akses fractional dan laporan. Pendapatan platform adalah fee bulanan dari waterfall, tarif belum diputuskan. Grounds entitas terpisah mendapat fee manajemen 2% dari bagian SPV, masih asumsi. Jangan gabungkan fee SPV sebagai revenue platform. Model punya kebutuhan modal nyata: Grounds harus mendanai akuisisi sebelum semua token laku, lalu memegang risiko inventory dan cadangan. Sumber modal, struktur hukum, izin dan partner produksi belum final. Channels owner networks dan sports communities adalah proposal, bukan traction. Tidak menganggap langganan PoS atau issuance fee sebagai revenue yang sudah ditetapkan.',
  },
  {
    title: 'Open the upside.', chapter: 'The next step', className: 'closing', seconds: 20,
    body: `<div class="closing-photo"><img src="/assets/basketball.jpg" alt="Basketball hoop and ball, illustrative sports photography"/></div><div class="closing-main"><h2>Open<br>the upside.</h2><p class="closing-tagline">A venue can serve more<br>than the people on its court.</p><div class="closing-ask"></div><a class="closing-repo" href="https://github.com/senarais/opengrounds" target="_blank" rel="noopener noreferrer">github opengrounds ↗</a><div class="closing-status"><span>ETHJKT 2026 / Ethereum Sepolia</span></div></div><div class="closing-court" aria-hidden="true"><svg viewBox="0 0 700 700"><g fill="none" stroke="#F8FAFC" stroke-width="2"><path class="closing-court-line" pathLength="1" d="M55 645V55h590v590M55 420a295 295 0 0 1 590 0M250 55v190h200V55M250 245a100 100 0 0 0 200 0"/></g></svg></div>`,
    source: '',
    notes: 'Tutup singkat: Open Grounds menghubungkan venue produktif dengan akses modal dan partisipasi atas hak manfaat ekonomi. Next step yang diusulkan adalah validasi satu venue bersama owner, reviewer independen, counsel dan penyedia pembayaran. Tidak mengklaim ada pilot atau partnership. Web dan kontrak ada; full end-to-end Sepolia belum terverifikasi menurut status proyek. Rupiah, split, escrow dan pembayaran akuisisi disimulasikan. Open Grounds belum berizin; aset bukan jaminan, imbal hasil dan likuiditas tidak dijamin. Tidak perlu mencantumkan nama anggota tim.',
  }
];
